apiVersion: v1
kind: Service
metadata:
  name: {yourname}-service
  namespace: {yourname}-demo-namespace
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {yourname}
  sessionAffinity: None
  type: LoadBalancer
status: {}
